apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: user-service
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: conga-platform
  conga.io/site-group: CSG1
  conga.io/sync-wave: "2"

images:
- name: ghcr.io/testorg08/user-service
  newTag: latest